### ISSUE TITLE
New Langs

### ISSUE THREAD

**Issue by maximuslotro** [maximuslotro/SignStory#1]
@Kofola45cz I noticed that you created a pull request at [https://github.com/Team-Fruit/SignPicture/pull/66](https://github.com/Team-Fruit/SignPicture/pull/66 ). This mod here is a extended and currently developed version of the SignPicture mod with all the original functions that the SignPicture mod included. Feel free to create pull request and upload your Czech lang file. :)

**Comment by Kofola45cz** [comment]
@maximuslotro 
Hello, and your improved version from SignPicture is available somewhere to download officially, like from CurseForge or something?
Otherwise, if I understand, this version fixes and improves, so it will be compatible for worlds (and server) where SignPicture was used?

**Comment by maximuslotro** [comment]
This mod implements the signpicture mod, while adding a new functionality to load text from a file and paste it across multiple signs. using (/SignStory toggle_functionality) toggle between using the SignStory sub commands and the SignPicture gui.  The Functionality for placing and view pictures instead of just a sign is a 1:1 from the original mod. I used to use the SignPicture mod, but after implimenting its code to make my own mod for placing many sings from text, i found it was possible to make both mods into one mod. So this mod will work and look eactly how the original mod did. Also i haven't gotten around to making a Curseforge page for this mod yet. Only released it several days ago and I'm still improving it.

**Comment by maximuslotro** [comment]
@Kofola45cz This mod implements the signpicture mod, while adding a new functionality to load text from a file and paste it across multiple signs. using (/SignStory toggle_functionality) toggle between using the SignStory sub commands and the SignPicture gui.  The Functionality for placing and view pictures instead of just a sign is a 1:1 from the original mod. I used to use the SignPicture mod, but after implimenting its code to make my own mod for placing many sings from text, i found it was possible to make both mods into one mod. So this mod will work and look eactly how the original mod did. Also i haven't gotten around to making a Curseforge page for this mod yet. Only released it several days ago and I'm still improving it. I would be happy if your could contribute to it. :) (Since the original mod is dead in development).

**Comment by Kofola45cz** [comment]
@maximuslotro I see. Anyway, when I have time, I'll check it out. 😉

**Comment by maximuslotro** [comment]
Thanks. I merged it. :)
