### ISSUE TITLE
SignPicture - "line in the air" 1pixel for image with partially empty content...

### ISSUE THREAD

**Issue by Kofola45cz** [maximuslotro/SignStory#12]
- SignPicture has a problem with images that have instead of no texture (PNG), line in the air / the top band (1pixel) is for some reason placed on the top edge of the area
.

I have consulted with a friend yet so he can better describe the problem to you.
- Cyclic texture is set - so when the texture is smoothed, it transitions smoothly between edges and the bottom edge flows into the top edge and the sides too, this would be best seen on a differently rotated triangle
- I have no idea how the GL parameters allow you to set non-cyclic textures, or if it needs to be handled differently...
- The reason why this is the case is that an otherwise square texture normally repeats to fill the whole area, and you need to smooth it out correctly - so it's correct that it normally behaves this way
- Oddly enough, I can get around this by adding blank margins to each image

![2022-07-24_17 06 01](https://user-images.githubusercontent.com/22054484/180653372-cc0d5836-874e-430d-95bc-ecaf0d54c904.png)
![2022-07-24_17 06 05](https://user-images.githubusercontent.com/22054484/180653374-eace87f6-a8fc-416e-b590-4bd313b03537.png)
Test Image: https://hajdam.zdechov.net/s/zn-fx4x-c.png
Both versions (SignPicture/SignStory)

-> not sure if it can be fixed, if not, never mind.

**Comment by maximuslotro** [comment]
I currently don't know how to fix this, Image processing is beyond my java knowledge. Adding blank margins around the image looks like the best fix.
