### ISSUE TITLE
SignPicture - plugin - image index paleta

### ISSUE THREAD

**Issue by Kofola45cz** [maximuslotro/SignStory#13]
I have consulted with a friend yet so he can better describe the problem to you.
- There's some dithering and the transparency isn't working. The correct fix would probably be to convert the image to true color before sending it to the texture..
With color images it's even easier to see how broken it is...
- plugin does not work correctly with images with indexed palette
- That's already a problem with SignPicture that it makes it do that rough texture

In GUI
![2022-07-24_18 17 55](https://user-images.githubusercontent.com/22054484/180656638-0f9e6d2c-6bbf-40a9-9e29-3a3685b3e08c.png)
Preview:
![2022-07-24_18 17 16](https://user-images.githubusercontent.com/22054484/180656606-3156bc68-40b9-408d-99b8-36453592aeff.png)
Placing:
![2022-07-24_18 17 50](https://user-images.githubusercontent.com/22054484/180656629-7938e950-f8bf-409f-8eb8-d1ceaab6caa9.png)

Source images with which SignPicture has a problem
![indexed-palette](https://user-images.githubusercontent.com/22054484/180656662-7d9abc63-408c-47fa-8fd6-28eeae1826f5.png)
![indexed-palette-2](https://user-images.githubusercontent.com/22054484/180656663-bcfa1241-279c-4c1d-8922-1769803789a5.png)

Both versions (SignPicture/SignStory)

**Comment by maximuslotro** [comment]
In the gui the image is a solid picture, when is Preview, the image is a transparent ghost image, and when place it is a rendered texture. ~~This looks like a problem with signpicture not having the code to handle transparent images. The coding to make this work is out of my current knowledge. I guess a way around this is to trim transparent sections from images?~~

**Comment by Kofola45cz** [comment]
@maximuslotro So if I understand, as long as there is a transparent spot, see the black part, the green part/blue part won't have a solid texture/color either?

**Comment by maximuslotro** [comment]
Nm what i said before, looking at other images, transparency should show through.
![2022-08-02_14 25 48](https://user-images.githubusercontent.com/61996354/182457473-6bbc1f92-827c-4579-8cb3-130037cec2c7.png)

**Comment by maximuslotro** [comment]
![2022-08-02_14 30 50](https://user-images.githubusercontent.com/61996354/182458058-b92d09b7-d6b4-4572-b6d1-f35d8fe55637.png)
Also i tried the image you posted and got this result. Are you not getting this? Maybe this issue is related to something outside of signpicture/signstory? because transparent images work for me on both signpicture/signstory.

**Comment by maximuslotro** [comment]
Possibly the same problem as #12.

**Comment by Kofola45cz** [comment]
@maximuslotro ok, I understand, I'll try to find out what it could be 🤔
_of course I understand that it's probably just an incompatibility with some mod or something or setting Minecraft. And I don't blame you._

**Comment by maximuslotro** [comment]
Would it be so hard to live in a perfect world where everything behaved nicely. 😭  `YES`
