### ISSUE TITLE
Suggestion for adjustable blur

### ISSUE THREAD

**Issue by Kofola45cz** [maximuslotro/SignStory#14]
- Option to set at what distance and how much to focus, even render quality resolution
- For example, the ability to set the distance at which images should be displayed
- Like add more setting options that would allow players to have Shaders or OptiFine, so depending on how good the PC is, the player could adjust the quality...
- of course, within reason.

![2022-07-24_18 42 23](https://user-images.githubusercontent.com/22054484/180657506-88d1d330-f6c7-4c83-9e5d-1e9d11dd779a.png)
![2022-07-24_18 42 26](https://user-images.githubusercontent.com/22054484/180657509-bdf942f0-4049-486a-a5c5-3aa838fe0026.png)
![2022-07-24_18 42 31](https://user-images.githubusercontent.com/22054484/180657510-eec3855e-b290-49e9-8226-bf33be1b73b2.png)
![2022-07-24_18 42 42](https://user-images.githubusercontent.com/22054484/180657511-4a19a901-2fcb-4359-951e-f28fede3fdd4.png)

**Comment by maximuslotro** [comment]
Tbh, I'm not a wizard at forge. I have no knowledge how to add third-part mod options to optfine, idk if its possible to set different image resolutions/quality for different distances.

**Comment by Kofola45cz** [comment]
@maximuslotro  I know that you are not a wizard and I know that many ideas will die because of the complexity, but better to mention it than to keep it to yourself 😄

**Comment by maximuslotro** [comment]
Very true, it never hurts to put ides out there.
